set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set smartindent
set paste

execute pathogen#infect()
syntax on
filetype plugin indent on


syntax enable
colorscheme solarized

colorscheme zenburn
set nu


:imap jj <Esc>
